// <auto-generated />
using System;
using MeusicRuchama;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MeusicRuchama.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20251202132127_m3")]
    partial class m3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LessonsStudents", b =>
                {
                    b.Property<int>("lessonsid")
                        .HasColumnType("int");

                    b.Property<int>("studentsid")
                        .HasColumnType("int");

                    b.HasKey("lessonsid", "studentsid");

                    b.HasIndex("studentsid");

                    b.ToTable("LessonsStudents");
                });

            modelBuilder.Entity("MeusicRuchama.Entities.Lessons", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("day")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("end")
                        .HasColumnType("time");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeOnly>("start")
                        .HasColumnType("time");

                    b.Property<int>("teacherId")
                        .HasColumnType("int");

                    b.Property<int>("teachersid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("teachersid");

                    b.ToTable("lessons");
                });

            modelBuilder.Entity("MeusicRuchama.Entities.Students", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("students");
                });

            modelBuilder.Entity("MeusicRuchama.Entities.Teachers", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("teachers");
                });

            modelBuilder.Entity("LessonsStudents", b =>
                {
                    b.HasOne("MeusicRuchama.Entities.Lessons", null)
                        .WithMany()
                        .HasForeignKey("lessonsid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeusicRuchama.Entities.Students", null)
                        .WithMany()
                        .HasForeignKey("studentsid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MeusicRuchama.Entities.Lessons", b =>
                {
                    b.HasOne("MeusicRuchama.Entities.Teachers", "teachers")
                        .WithMany("lessons")
                        .HasForeignKey("teachersid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("teachers");
                });

            modelBuilder.Entity("MeusicRuchama.Entities.Teachers", b =>
                {
                    b.Navigation("lessons");
                });
#pragma warning restore 612, 618
        }
    }
}
